### ISSUE TITLE
Update for IDEA 2017.2

### ISSUE THREAD

**Issue by phdoerfler** [NixOS/nix-idea#12]
My installation of 2017.2 claims this plug-in is not compatible. Is it supped to work with that version?

```
2:31 PM	Plugin Error
			Problems found loading plugins:
			The following plugins are incompatible with the current IDE build: NixIDEA
```

**Comment by pSub** [comment]
Version 0.2.0.1 does not work with IDEA 2017.2. However current HEAD /is/ compatible. I'll try to figure out how to release a new version.

**Comment by pSub** [comment]
I've released v0.2.1.0 which should work fine with IDEA 2017.1.

**Comment by phdoerfler** [comment]
Is there any chance we will see a binary version of this?
https://plugins.jetbrains.com/plugin/8607-nixidea still shows 0.2.0.1 as being the latest version.

**Comment by pSub** [comment]
Unfortunately I cannot upload a new release to the jetbrains repository. I think the only person able to is @edwtjo. I just wrote him an email about this.

**Comment by chris-martin** [comment]
@pSub @edwtjo Sorry to be a bother, but what's the status of this?

**Comment by pSub** [comment]
I haven't received a response from @edwtjo yet. Maybe I should try contact the Intellij-Plugin-Team and ask if they can grant me access.

**Comment by pSub** [comment]
I've uploaded the release to https://plugins.jetbrains.com. Thanks to @edwtjo for granting me access.

**Comment by chris-martin** [comment]
Thank you!
